<?xml version="1.0"?>
<package format="3">
  <name>fast_lio_localization_sc_qn</name>
  <version>0.0.0</version>

  <description>
    This repository is a map-based localization implementation combining FAST-LIO2 with Quatro, Nano-GICP, and ScanContext
  </description>
  <maintainer email="eungchang_mason@kaist.ac.kr">Eungchang Mason Lee</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>pcl_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>message_filters</depend>
  <depend>nano_gicp</depend>
  <depend>quatro</depend>
  <depend>yaml-cpp</depend>
  <depend>gtsam</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>

  <export>
      <build_type>ament_cmake</build_type>
  </export>
</package>
